name: Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Your region

    - name: Sync to S3
      run: aws s3 sync . s3://staging.dcprivacysummit.org --delete --exclude ".git/*"

  
    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id E3IN32OXEJELM7 --paths "/*"
